export {default as Login} from './login/index.jsx'
export {default as CashierLayout} from './cashier/CashierLayout.jsx'
export {default as TakeOrder} from './cashier/TakeOrder.jsx'
export {default as OrderMenu} from './cashier/customerOrder/OrderMenu.jsx'
export {default as SelectTable} from './cashier/customerOrder/OrderMenu.jsx'